title: FlipkartGrid-2.0 Noise Suppression Challenge
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Team Comrade's solution to the noise suppression challenge conducted by Flipkart
baseurl: "/FlipkartGrid2.0/"
url: "https://mukundvarmat.github.io/FlipkartGrid2.0/"

# Build settings
markdown: kramdown
theme: jekyll-theme-primer
plugins:
  - jekyll-feed